/** 动画曲线 */
export const enum EEasing {
    /** 匀速 */
    linear = 'linear',
    /** 不匀速 */
    /** 由快至慢 */
    easeInQuad = 'easeInQuad',
    easeOutQuad = 'easeOutQuad',
    easeInOutQuad = 'easeInOutQuad',
    /** 由快至慢，效果更强 */
    easeInCubic = 'easeInCubic',
    easeOutCubic = 'easeOutCubic',
    easeInOutCubic = 'easeInOutCubic',
    /** 由快至慢，效果更强 */
    easeInQuart = 'easeInQuart',
    easeOutQuart = 'easeOutQuart',
    easeInOutQuart = 'easeInOutQuart',
    /** 由快至慢，效果更强 */
    easeInQuint = 'easeInQuint',
    easeOutQuint = 'easeOutQuint',
    easeInOutQuint = 'easeInOutQuint',
    /** 由快至慢，比Quad弱 */
    easeInSine = 'easeInSine',
    easeOutSine = 'easeOutSine',
    easeInOutSine = 'easeInOutSine',
    /** 突然减速，效果较强 */
    easeInExpo = 'easeInExpo',
    easeOutExpo = 'easeOutExpo',
    easeInOutExpo = 'easeInOutExpo',
    /** 突然减速，效果较弱 */
    easeInCirc = 'easeInCirc',
    easeOutCirc = 'easeOutCirc',
    easeInOutCirc = 'easeInOutCirc',
    /** 冲出终点后返回 */
    easeInBack = 'easeInBack',
    easeOutBack = 'easeOutBack',
    easeInOutBack = 'easeInOutBack'
}